woman(ann).
woman(july).
woman(mary).
woman(tatyana).
man(andrew).
man(ivan).
man(peter).
man(vasiliy).
waifu(X,Y).
p1:-not(waifu(ivan,ann)).
a1:-waifu(ivan,july).
p2:-waifu(peter,ann).
a2:-not(waifu(ivan,july)).
p3:-not(waifu(vasiliy,mary)).
a3:-waifu(andrew,july).
p4:-waifu(peter,july).
a4:-waifu(ivan,tatyana).
p5:-not(waifu(peter, mary)).
a5:-not(waifu(ivan,tatyana)).
p6:-waifu(andrew,july).
a6:-waifu(ivan,mary).

r1:-p1,!,a1.
r1.
r2:-p2,!,a2.
r2.
r3:-p3,!,a3.
r3.
r4:-p4,!,a4.
r4.
r5:-p5,!,a5.
r5.
r6:-p6,!,a6.
r6.

an(ivan,ann):-waifu(ivan,ann),r1,r2,r3,r4,r5,r6.
an(ivan,july):-waifu(ivan,july),r1,r2,r3,r4,r5,r6.
an(ivan,mary):-waifu(ivan,mary),r1,r2,r3,r4,r5,r6.
an(ivan,tatyana):-waifu(ivan,tatyana),r1,r2,r3,r4,r5,r6.
an(peter,ann):-waifu(peter,ann),r1,r2,r3,r4,r5,r6.
an(peter,july):-waifu(peter,july),r1,r2,r3,r4,r5,r6.
an(peter,mary):-waifu(peter,mary),r1,r2,r3,r4,r5,r6.
an(peter,tatyana):-waifu(peter,tatyana),r1,r2,r3,r4,r5,r6.
an(vasiliy,ann):-waifu(vasiliy,ann),r1,r2,r3,r4,r5,r6.
an(vasiliy,july):-waifu(vasiliy,july),r1,r2,r3,r4,r5,r6.
an(vasiliy,mary):-waifu(vasiliy,mary),r1,r2,r3,r4,r5,r6.
an(vasiliy,tatyana):-waifu(vasiliy,tatyana),r1,r2,r3,r4,r5,r6.
an(andrew,ann):-waifu(andrew,ann),r1,r2,r3,r4,r5,r6.
an(andrew,july):-waifu(andrew,july),r1,r2,r3,r4,r5,r6.
an(andrew,mary):-waifu(andrew,mary),r1,r2,r3,r4,r5,r6.
an(andrew,tatyana):-waifu(andrew,tatyana),r1,r2,r3,r4,r5,r6.
